# Generated by Django 5.0.6 on 2026-08-19 00:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('pluggy', 'Pluggy'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('payload', models.JSONField()),
                ('signature_valid', models.BooleanField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processed', 'Processado'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'webhook_events',
                'indexes': [models.Index(condition=models.Q(('status', 'pending')), fields=['status'], name='webhook_pending_idx')],
            },
        ),
    ]
