# Generated by Django 5.0.6 on 2026-08-19 00:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(choices=[('groceries', 'Mercado'), ('food', 'Alimentação'), ('transport', 'Transporte'), ('subscriptions', 'Assinaturas'), ('health', 'Saúde'), ('leisure', 'Lazer'), ('housing', 'Moradia'), ('income', 'Salário'), ('extra_income', 'Renda Extra'), ('credit_card', 'Cartão de crédito'), ('loan', 'Empréstimo'), ('debt', 'Dívida'), ('other', 'Outros')], max_length=20, unique=True)),
                ('name_pt', models.CharField(max_length=50)),
                ('color_light', models.CharField(max_length=7)),
                ('color_dark', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('checking', 'Conta corrente'), ('credit_card', 'Cartão de crédito'), ('manual', 'Manual')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('provider_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='connections.connection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='CategorizationRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_type', models.CharField(choices=[('merchant', 'Estabelecimento'), ('description_contains', 'Descrição contém')], max_length=25)),
                ('match_value', models.CharField(max_length=255)),
                ('hits_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.category')),
            ],
            options={
                'db_table': 'categorization_rules',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.BigIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('category_source', models.CharField(choices=[('provider', 'Provedor'), ('rule', 'Regra'), ('llm', 'LLM'), ('user', 'Usuário')], max_length=10)),
                ('origin', models.CharField(choices=[('bank', 'Banco'), ('whatsapp', 'WhatsApp'), ('web', 'Web')], max_length=10)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_provider_data', models.JSONField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'indexes': [models.Index(fields=['user', '-date'], name='tx_user_date_idx'), models.Index(fields=['user', 'category', 'date'], name='tx_user_cat_date_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_transaction_id__isnull', False)), fields=('account', 'provider_transaction_id'), name='uniq_provider_transaction_id_per_account'),
        ),
    ]
