# Generated by Django 5.0.6 on 2026-08-19 05:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('stock', 'Ação'), ('fii', 'FII'), ('crypto', 'Cripto')], max_length=10)),
                ('symbol', models.CharField(max_length=30)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('avg_price_cents', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investment_holdings',
            },
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(fields=('user', 'kind', 'symbol'), name='uniq_holding_user_kind_symbol'),
        ),
    ]
