# Generated by Django 5.0.6 on 2026-08-19 00:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('pluggy', 'Pluggy')], default='pluggy', max_length=20)),
                ('provider_item_id', models.CharField(max_length=255)),
                ('access_token_encrypted', models.TextField()),
                ('institution_name', models.CharField(max_length=150)),
                ('institution_logo', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('syncing', 'Sincronizando'), ('active', 'Ativa'), ('error', 'Erro'), ('revoked', 'Revogada')], default='syncing', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'connections',
            },
        ),
    ]
