# Generated by Django 5.0.6 on 2026-08-19 00:33

import django.db.models.deletion
import uuid
import whatsapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_e164', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('pairing_code', models.CharField(default=whatsapp.models._generate_pairing_code, max_length=6)),
                ('pairing_expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('active', 'Ativo'), ('unlinked', 'Desvinculado')], default='pending', max_length=10)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'whatsapp_links',
            },
        ),
        migrations.CreateModel(
            name='WhatsappMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('in', 'Recebida'), ('out', 'Enviada')], max_length=3)),
                ('body', models.TextField()),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatsapp_messages',
                'indexes': [models.Index(fields=['user', '-created_at'], name='wa_msg_user_created_idx')],
            },
        ),
    ]
